// Unsplash images — free, no auth required, reliable on Vercel
const imgs = {
  apartment1: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=500&fit=crop",
  apartment2: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=500&fit=crop",
  apartment3: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=500&fit=crop",
  villa1:     "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=500&fit=crop",
  villa2:     "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=500&fit=crop",
  floor1:     "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=500&fit=crop",
  floor2:     "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=500&fit=crop",
  duplex:     "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=500&fit=crop",
  plot:       "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=500&fit=crop",
  commercial: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&h=500&fit=crop",
  house:      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=500&fit=crop",
  building:   "https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=800&h=500&fit=crop",
}

export const properties = [
  {
    id: 1,
    title: "Pruthvi Royal",
    location: "Gottigere, Bannerghatta Road",
    price: "₹65 Lac",
    bedrooms: 2,
    bathrooms: 2,
    area: "1154 sq.ft",
    type: "Builder Floor",
    featured: true,
    image: imgs.floor1,
    description: "2 BHK Builder Floor on Ground Floor. 1154 sq.ft of well-planned living space in Gottigere, Bannerghatta Road.",
  },
  {
    id: 2,
    title: "Purva Panorama – 3 BHK",
    location: "Kalena Agrahara Metro Station, Bannerghatta Road",
    price: "₹1.85 Cr",
    bedrooms: 3,
    bathrooms: 2,
    area: "1500 sq.ft",
    type: "Apartment",
    featured: true,
    image: imgs.apartment1,
    description: "Spacious 3 BHK apartment on the 7th Floor at Purva Panorama, steps from Kalena Agrahara Metro Station.",
  },
  {
    id: 3,
    title: "Purva Panorama – 2 BHK",
    location: "Kalena Agrahara Metro Station, Bannerghatta Road",
    price: "₹1.40 Cr",
    bedrooms: 2,
    bathrooms: 2,
    area: "1325 sq.ft",
    type: "Apartment",
    featured: true,
    image: imgs.apartment2,
    description: "Well-appointed 2 BHK apartment on the 6th Floor at Purva Panorama, near Kalena Agrahara Metro Station.",
  },
  {
    id: 4,
    title: "Meenakshi Layout Builder Floor",
    location: "Meenakshi Layout, Bannerghatta Road",
    price: "₹1.05 Cr",
    bedrooms: 3,
    bathrooms: 2,
    area: "1430 sq.ft",
    type: "Builder Floor",
    featured: true,
    image: imgs.floor2,
    description: "2, 3 & 4 BHK options across Ground, 2nd, 3rd & 4th Floor in Meenakshi Layout, Bannerghatta Road.",
  },
  {
    id: 5,
    title: "Prestige White Meadows",
    location: "Whitefield, Bangalore",
    price: "₹11.5 Cr",
    bedrooms: 4,
    bathrooms: 5,
    area: "6651 sq.ft",
    type: "Villa",
    featured: true,
    image: imgs.villa1,
    description: "Prestigious 4.5 BHK semi-furnished villa, East-facing with 3 balconies, 3 parking spots and servant quarters.",
  },
  {
    id: 6,
    title: "Jains Aashraya",
    location: "Basavanpura, Bannerghatta Main Road",
    price: "₹1.57 Cr",
    bedrooms: 3,
    bathrooms: 2,
    area: "1487 sq.ft",
    type: "Apartment",
    featured: true,
    image: imgs.apartment3,
    description: "3 BHK apartment on the 5th Floor at Jains Aashraya, Basavanpura, Bannerghatta Main Road.",
  },
  {
    id: 7,
    title: "Mythreyi Vithola Apartment",
    location: "Near Kalena Agrahara Metro Station, Bannerghatta Main Road",
    price: "₹1.10 Cr",
    bedrooms: 2,
    bathrooms: 2,
    area: "1450 sq.ft",
    type: "Apartment",
    featured: false,
    image: imgs.apartment1,
    description: "2 BHK apartment on the 2nd Floor, conveniently located near Kalena Agrahara Metro Station.",
  },
  {
    id: 8,
    title: "MLA Layout Builder Floor",
    location: "MLA Layout, Nobonagar",
    price: "₹2.60 Cr",
    bedrooms: 4,
    bathrooms: 3,
    area: "4800 sq.ft",
    type: "Builder Floor",
    featured: false,
    image: imgs.floor1,
    description: "G+4 building spanning 4800 sq.ft in MLA Layout, Nobonagar. Ideal for investment or owner-occupancy.",
  },
  {
    id: 9,
    title: "Himagiri Meadows Duplex",
    location: "Bannerghatta Main Road",
    price: "₹2.45 Cr",
    bedrooms: 3,
    bathrooms: 3,
    area: "1600 sq.ft",
    type: "Duplex",
    featured: false,
    image: imgs.duplex,
    description: "Stylish duplex home of 1600 sq.ft on Bannerghatta Main Road offering double-floor living.",
  },
  {
    id: 10,
    title: "Doddakammanahalli Plot",
    location: "Doddakammanahalli, Bannerghatta Road",
    price: "₹7,500/sq.ft",
    bedrooms: 0,
    bathrooms: 0,
    area: "30×40 / 60×40",
    type: "Plot",
    featured: false,
    image: imgs.plot,
    description: "Residential plot available in 30×40 and 60×40 sizes at ₹7,500 per sq.ft in Doddakammanahalli.",
  },
  {
    id: 11,
    title: "Raja Iyers Block 2 Plot",
    location: "Doddakammanahalli, Bannerghatta Road",
    price: "₹7,800/sq.ft",
    bedrooms: 0,
    bathrooms: 0,
    area: "30×40",
    type: "Plot",
    featured: false,
    image: imgs.plot,
    description: "30×40 residential plot in Raja Iyers Block 2, Doddakammanahalli at ₹7,800 per sq.ft.",
  },
  {
    id: 12,
    title: "Commercial Site – Gottigere (13K sq.ft)",
    location: "Gottigere",
    price: "₹0.55/sq.ft (Rent)",
    bedrooms: 0,
    bathrooms: 0,
    area: "13,000 sq.ft",
    type: "Commercial",
    featured: false,
    image: imgs.commercial,
    description: "13,000 sq.ft commercial site available for rent at ₹0.55 per sq.ft in Gottigere.",
  },
  {
    id: 13,
    title: "Commercial Site – Gottigere (35K sq.ft)",
    location: "Gottigere",
    price: "₹0.50/sq.ft (Rent)",
    bedrooms: 0,
    bathrooms: 0,
    area: "35,000 sq.ft",
    type: "Commercial",
    featured: false,
    image: imgs.commercial,
    description: "Large 35,000 sq.ft commercial site available for rent at ₹0.50 per sq.ft in Gottigere.",
  },
  {
    id: 14,
    title: "Valmark City Ville",
    location: "Hulimavu",
    price: "₹4.15 Cr",
    bedrooms: 3,
    bathrooms: 3,
    area: "2180 sq.ft",
    type: "Apartment",
    featured: false,
    image: imgs.apartment2,
    description: "Premium 3 BHK apartment of 2180 sq.ft at Valmark City Ville, Hulimavu.",
  },
  {
    id: 15,
    title: "Independent House",
    location: "Hulimavu",
    price: "₹1.60 Cr",
    bedrooms: 2,
    bathrooms: 2,
    area: "1250 sq.ft",
    type: "Independent House",
    featured: false,
    image: imgs.house,
    description: "2 BHK independent house of 1250 sq.ft in Hulimavu.",
  },
  {
    id: 16,
    title: "Residency Building",
    location: "Meenakshi Layout, Bannerghatta Road",
    price: "₹3.68 Cr",
    bedrooms: 3,
    bathrooms: 3,
    area: "5600 sq.ft",
    type: "Residency Building",
    featured: false,
    image: imgs.building,
    description: "5600 sq.ft residency building with 4 units of 3 BHK each in Meenakshi Layout, Bannerghatta Road.",
  },
]
